name: PIONEER Vision CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  colcon-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: galactic

      - name: Build rm_serial_driver and run tests
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: rm_serial_driver
          import-token: ${{ secrets.PAT }}
          target-ros2-distro: galactic

  docker-build-and-push:
    needs: colcon-build-and-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PAT }}
          persist-credentials: false

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/nolem/rm_pioneer_vision:base

      - name: Build and push desktop image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: BASE_IMAGE=osrf/ros:galactic-desktop
          tags: ghcr.io/nolem/rm_pioneer_vision:desktop, 
                ghcr.io/nolem/rm_pioneer_vision:latest
